version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: farmacia_backend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@host.docker.internal:5432/farmacia_db?schema=public
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: farmacia_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
